# Setup gradle memory
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Enable config cache
org.gradle.build-cache=true
org.gradle.configuration-cache=true

# The general release series for development build versioning
# TODO: Could use this for tag sanity checks during CI builds?
versionSeries=8.2

# Mappings
neoForge.parchment.minecraftVersion=1.21
neoForge.parchment.mappingsVersion=2024.07.28

# ===========================
# Combined Project Properties
# ===========================

# Modrinth support
modrinth_projectId = 49ZofO4f
curseforge_projectId = 64578
