[versions]
minecraft = "1.20.1"
forge = "47.1.3"
almostUnified = "1.20.1-0.10.1"
jeiVersion = "15.20.0.129"
ccTweaked = "1.113.1"
jade = "11.13.2+forge"
athena = "3.1.2"
ae2 = { strictly = "[15.4,)", prefer = "15.4.10" }
mekanism = { strictly = "[1.20.1-10.4,)", prefer = "1.20.1-10.4.16.80" }
mekanismMod = { strictly = "[10.4.0,)", prefer = "10.4.16.80" } # workaround for Mek having MC version in the version specifier.
laserio = "5074767"
graphlib = { strictly = "[3.0.4, 3.1)", prefer = "3.0.5" }
ftbUltimine = { strictly = "[2001.1.7,2101)", prefer = "2001.1.7" }
embeddium = "0.3.31+mc1.20.1"
iris = "1.7.6+1.20.1"

[libraries]
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version = "23.0.0"}
#neoforgeTestFramework = { group = "net.neoforged", name = "testframework", version.ref = "neoforge"}

almostUnified = { group = "com.almostreliable.mods", name = "almostunified-forge", version.ref = "almostUnified" }
jeiCommonApi = { group = "mezz.jei", name = "jei-1.20.1-common-api", version.ref = "jeiVersion" }
jeiForgeApi = { group = "mezz.jei", name = "jei-1.20.1-forge-api", version.ref = "jeiVersion" }
jeiCommon = { group = "mezz.jei", name = "jei-1.20.1-common", version.ref = "jeiVersion" }
jeiForge = { group = "mezz.jei", name = "jei-1.20.1-forge", version.ref = "jeiVersion" }
ccTweakedCoreApi = { group = "cc.tweaked", name = "cc-tweaked-1.20.1-core-api", version.ref = "ccTweaked" }
ccTweakedForgeApi = { group = "cc.tweaked", name = "cc-tweaked-1.20.1-forge-api", version.ref = "ccTweaked" }
ccTweakedForge = { group = "cc.tweaked", name = "cc-tweaked-1.20.1-forge", version.ref = "ccTweaked" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
athena = { group = "maven.modrinth", name = "athena-ctm", version.ref = "athena" }
ae2 = { group = "appeng", name = "appliedenergistics2-forge", version.ref = "ae2" }
mekanism = { group = "mekanism", name = "Mekanism", version.ref = "mekanism" }
laserio = { group = "curse.maven", name = "laserio-626839", version.ref = "laserio" }
graphlib = { group = "dev.gigaherz.graph", name = "GraphLib3", version.ref = "graphlib"}
ftbUltimine = { group = "dev.ftb.mods", name = "ftb-ultimine-forge", version.ref = "ftbUltimine" }
embeddium = { group = "maven.modrinth", name = "embeddium", version.ref = "embeddium" }
iris = { group = "maven.modrinth", name = "iris", version.ref = "iris" }

junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.7.1"}
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[bundles]
jeiApi = ["jeiCommonApi", "jeiForgeApi"]
jei = ["jeiCommon", "jeiForge"]
ccTweakedApi = ["ccTweakedCoreApi", "ccTweakedForgeApi"]
