[versions]
almostUnified = "1.21.1-1.0.0"
jeiVersion = "30.2.0.18"
ccTweaked = "1.113.1"
jade = "26.2.8+neoforge"
athena = "4.7.3"
ae2 = { strictly = "[26.1.5-alpha,)", prefer = "26.1.5-alpha" }
mekanism = { strictly = "[1.21.1-10.7.0,)", prefer = "1.21.1-10.7.16.82" }
mekanismMod = { strictly = "[10.7.0,)", prefer = "10.7.16.82" } # workaround for Mek having MC version in the version specifier.
refinedStorage = { strictly = "[3.0.0-beta.1,)", prefer = "3.0.0-beta.1" }
laserio = "5648871"
graphlib = { strictly = "[3.0.4, 3.1)", prefer = "3.0.5" }
ftbLibrary = { strictly = "[26.1.1.1-SNAPSHOT, 26.2)", prefer = "26.1.1.1-SNAPSHOT" }
ftbUltimine = { strictly = "[26.1, 26.2)", prefer = "26.1.0.1-SNAPSHOT" }
curios = "15.0.0-beta.1+26.1"
sodium = "mc26.2-0.9.1-beta.2-neoforge"
iris = "1.11.1+26.2-neoforge"
mockito = "5.23.0"

[libraries]
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.0"}
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version = "23.0.0"}

#almostUnified = { group = "com.almostreliable.mods", name = "almostunified-neoforge", version.ref = "almostUnified" }
jeiCommonApi = { group = "mezz.jei", name = "jei-26.2-common-api", version.ref = "jeiVersion" }
jeiNeoforgeApi = { group = "mezz.jei", name = "jei-26.2-neoforge-api", version.ref = "jeiVersion" }
jeiCommon = { group = "mezz.jei", name = "jei-26.2-common", version.ref = "jeiVersion" }
jeiNeoforge = { group = "mezz.jei", name = "jei-26.2-neoforge", version.ref = "jeiVersion" }
#ccTweakedCoreApi = { group = "cc.tweaked", name = "cc-tweaked-1.21.1-core-api", version.ref = "ccTweaked" }
#ccTweakedForgeApi = { group = "cc.tweaked", name = "cc-tweaked-1.21.1-forge-api", version.ref = "ccTweaked" }
#ccTweakedForge = { group = "cc.tweaked", name = "cc-tweaked-1.21.1-forge", version.ref = "ccTweaked" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
athena = { group = "maven.modrinth", name = "athena-ctm", version.ref = "athena" }
ae2 = { group = "org.appliedenergistics", name = "appliedenergistics2", version.ref = "ae2" }
#mekanism = { group = "mekanism", name = "Mekanism", version.ref = "mekanism" }
refinedStorage = { group = "com.refinedmods.refinedstorage", name = "refinedstorage-neoforge", version.ref = "refinedStorage" }
#laserio = { group = "curse.maven", name = "laserio-626839", version.ref = "laserio" }
graphlib = { group = "dev.gigaherz.graph", name = "GraphLib3", version.ref = "graphlib"}
ftbLibrary = { group = "dev.ftb.mods", name = "ftb-library-neoforge", version.ref = "ftbLibrary" }
ftbUltimine = { group = "dev.ftb.mods", name = "ftb-ultimine-neoforge", version.ref = "ftbUltimine" }
curios = { group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curios" }
sodium = { group = "maven.modrinth", name = "sodium", version.ref = "sodium" }
iris = { group = "maven.modrinth", name = "iris", version.ref = "iris" }

junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.7.1"}
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito"}
mockitoJunit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito"}

[bundles]
jeiApi = ["jeiCommonApi", "jeiNeoforgeApi"]
jei = ["jeiCommon", "jeiNeoforge"]
#ccTweakedApi = ["ccTweakedCoreApi", "ccTweakedForgeApi"]
