name: Bug Report
description: Report a crash or an unexpected behaviour.
title: "Bug Report"
labels: [Type-Bug, Status-Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered. This helps us to avoid duplicates.
    options:
    - label: I did not find any existing issues.
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: Explain what is currently happening which you consider to be a bug.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: Explain what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: How to Test
    description: Explain, step-by-step what you did at the time of the problem. Describe factory setups/configurations if necessary.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: textarea
  attributes:
    label: Local Environment
    description: |
      examples:
         - **Operating System**: Windows
         - **Java Version**: Adoptium 16.0.2.7-hotspot
         - **Minecraft Version**: 1.20.1
         - **Version**: 6.0.0
         - **Other Mods**: Applied Energistics 2, Mekanism...
    value: |
        - **Operating System**: 
        - **Java version**: 
        - **Minecraft Version**: 
        - **Version**: 
        - **Other Mods**: Applied Energistics 2, Mekanism...
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Any Additional Information?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      If this is a particularly complex issue, consider something like a video clip or gif.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
