package com.enderio.machines.common.recipe;

import com.enderio.EnderIO;
import com.enderio.core.common.recipes.CountedIngredient;
import com.enderio.core.common.recipes.OutputStack;
import com.enderio.machines.common.blockentity.AlloySmelterBlockEntity;
import com.enderio.machines.common.blockentity.PrimitiveAlloySmelterBlockEntity;
import com.enderio.machines.common.init.MachineRecipes;
import com.enderio.machines.common.io.item.MultiSlotAccess;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.minecraft.core.NonNullList;
import net.minecraft.core.RegistryAccess;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.item.crafting.RecipeType;
import net.minecraft.world.level.Level;
import net.minecraftforge.common.crafting.CraftingHelper;
import net.minecraftforge.items.IItemHandlerModifiable;
import net.minecraftforge.items.wrapper.RecipeWrapper;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class AlloySmeltingRecipe implements MachineRecipe<AlloySmeltingRecipe.ContainerWrapper> {

    private final ResourceLocation id;
    private final List<CountedIngredient> inputs;
    private final ItemStack output;
    private final int energy;
    private final float experience;
    private final boolean isSmelting;

    public AlloySmeltingRecipe(ResourceLocation id, List<CountedIngredient> inputs, ItemStack output, int energy, float experience, boolean isSmelting) {
        if (isSmelting && inputs.size() > 1) {
            throw new IllegalArgumentException("More than one smelting ingredient given");
        }
        
        this.id = id;
        this.inputs = inputs;
        this.output = output;
        this.energy = energy;
        this.experience = experience;
        this.isSmelting = isSmelting;
    }

    public AlloySmeltingRecipe(ResourceLocation id, List<CountedIngredient> inputs, ItemStack output, int energy, float experience) {
        this(id, inputs, output, energy, experience, false);
    }

    /**
     * Get the inputs for the alloy smelting recipe.
     */
    public List<CountedIngredient> getInputs() {
        return inputs;
    }

    /**
     * Get the amount of experience generated by the recipe.
     */
    public float getExperience() {
        return experience;
    }

    public boolean isSmelting() {
        return isSmelting;
    }

    @Override
    public int getBaseEnergyCost() {
        return energy;
    }

    @Override
    public NonNullList<Ingredient> getIngredients() {
        return NonNullList.of(Ingredient.EMPTY, inputs.stream().map(CountedIngredient::ingredient).toArray(Ingredient[]::new));
    }

    @Override
    public boolean matches(ContainerWrapper container, Level level) {
        if (inputs.isEmpty()) {
            return false;
        }

        // Simpler smelting match logic
        if (isSmelting) {
            int emptyCount = 0;

            for (int i = 0; i < 3; i++) {
                var slotItem = container.getItem(i);

                if (slotItem.isEmpty()) {
                    emptyCount++;
                    continue;
                }

                if (!inputs.get(0).test(slotItem)) {
                    return false;
                }
            }

            return emptyCount < 3;
        }

        // Trace which input items are matched, and which slots have been used for matching.
        boolean[] matchedInputs = new boolean[3];
        var slotAccess = container.getSlotAccess();

        // Iterate over the slots
        for (int i = 0; i < 3; i++) {
            // Iterate over the inputs
            for (int j = 0; j < 3; j++) {
                // If this ingredient has been matched already, continue
                if (matchedInputs[j]) {
                    continue;
                }

                var slotItem = slotAccess.get(i).getItemStack(container);

                if (j < inputs.size()) {
                    // If we expect an input, test we have a match for it.
                    if (inputs.get(j).test(slotItem)) {
                        matchedInputs[j] = true;
                        break;
                    }
                } else if (slotItem.isEmpty()) {
                    // If we don't expect an input, make sure we have a blank for it.
                    matchedInputs[j] = true;
                    break;
                }
            }
        }

        // If we matched all our ingredients, we win!
        for (int i = 0; i < 3; i++) {
            if (!matchedInputs[i]) {
                return false;
            }
        }

        return true;
    }

    @Override
    public List<OutputStack> craft(ContainerWrapper container, RegistryAccess registryAccess) {
        ItemStack outputStack = output.copy();
        if (isSmelting) {
            outputStack.setCount(outputStack.getCount() * container.inputsTaken);
        }

        return List.of(OutputStack.of(outputStack));
    }

    @Override
    public List<OutputStack> getResultStacks(RegistryAccess registryAccess) {
        return List.of(OutputStack.of(output.copy()));
    }

    @Override
    public ResourceLocation getId() {
        return id;
    }

    @Override
    public RecipeSerializer<?> getSerializer() {
        return MachineRecipes.ALLOY_SMELTING.serializer().get();
    }

    @Override
    public RecipeType<?> getType() {
        return MachineRecipes.ALLOY_SMELTING.type().get();
    }

    /**
     * The recipe container.
     * This acts as additional context.
     */
    public static class ContainerWrapper extends RecipeWrapper {

        private final boolean isPrimitive;
        private int inputsTaken;

        public ContainerWrapper(boolean isPrimitive, IItemHandlerModifiable inv) {
            super(inv);
            this.isPrimitive = isPrimitive;
        }

        public MultiSlotAccess getSlotAccess() {
            // Instead of a bool we could just pass the slot accesses, but a bool is probably cheaper to do.
            return isPrimitive ? PrimitiveAlloySmelterBlockEntity.INPUTS : AlloySmelterBlockEntity.INPUTS;
        }

        public int getInputsTaken() {
            return inputsTaken;
        }

        public void setInputsTaken(int inputsTaken) {
            this.inputsTaken = inputsTaken;
        }
    }

    public static class Serializer implements RecipeSerializer<AlloySmeltingRecipe> {

        @Override
        public AlloySmeltingRecipe fromJson(ResourceLocation recipeId, JsonObject serializedRecipe) {
            // Load ingredients
            JsonArray jsonInputs = serializedRecipe.getAsJsonArray("inputs");
            List<CountedIngredient> inputs = new ArrayList<>(jsonInputs.size());
            for (int i = 0; i < jsonInputs.size(); i++) {
                inputs.add(i, CountedIngredient.fromJson(jsonInputs.get(i).getAsJsonObject()));
            }

            // Load result, energy and experience.
            ItemStack result = CraftingHelper.getItemStack(serializedRecipe.getAsJsonObject("result"), true);
            int energy = serializedRecipe.get("energy").getAsInt();
            float experience = serializedRecipe.get("experience").getAsFloat();
            boolean isSmelting = serializedRecipe.has("is_smelting") && serializedRecipe.get("is_smelting").getAsBoolean();
            return new AlloySmeltingRecipe(recipeId, inputs, result, energy, experience, isSmelting);
        }

        @Nullable
        @Override
        public AlloySmeltingRecipe fromNetwork(ResourceLocation recipeId, FriendlyByteBuf buffer) {
            try {
                List<CountedIngredient> ingredients = buffer.readList(CountedIngredient::fromNetwork);
                ItemStack result = buffer.readItem();
                int energy = buffer.readInt();
                float experience = buffer.readFloat();
                return new AlloySmeltingRecipe(recipeId, ingredients, result, energy, experience);
            } catch (Exception ex) {
                EnderIO.LOGGER.error("Error reading alloy smelting recipe from packet.", ex);
                throw ex;
            }
        }

        @Override
        public void toNetwork(FriendlyByteBuf buffer, AlloySmeltingRecipe recipe) {
            try {
                buffer.writeCollection(recipe.inputs, (buf, ing) -> ing.toNetwork(buf));
                buffer.writeItem(recipe.output);
                buffer.writeInt(recipe.energy);
                buffer.writeFloat(recipe.experience);
            } catch (Exception ex) {
                EnderIO.LOGGER.error("Error writing alloy smelting recipe to packet.", ex);
                throw ex;
            }
        }
    }
}
